version: "3.7"
services:
  # <DBs>
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
    env_file: 
      - './users/.env' 
      
  # </DBs>

  ## s<ervices>
  app:
    build: ./services/users
    restart: always
    secrets:
      - db-password
    env_file: 
      - './services/users/.env'
    volumes:
      - ".:/app"
      - "./docker/database.yml:/app/config/database.yml"
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - backend-network
      - frontend-network
  ## </services>


  # Sideqik
  # sidekiq:
  #   depends_on:
  #     - 'db'
  #     - 'redis'
  #   build: ./services/users
  #   command: sidekiq -C config/sidekiq.yml.erb
  #   volumes:
  #     - '.:/app'
    # env_file:
    #   - '.env'

  # <Proxy> reverse proxy for internal services map
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - frontend-network
    # </Proxy>

volumes:
  db-data:
  redis:
secrets:
  db-password:
    file: db/password.txt
networks:
  backend-network:
  frontend-network: